// flow-typed signature: 4a6395ef1ed0874c926f7c9084d7d194
// flow-typed version: <<STUB>>/redux-request-state_v^1.1.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-request-state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-request-state' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-request-state/selectors' {
  declare module.exports: any;
}

declare module 'redux-request-state/tests/index' {
  declare module.exports: any;
}

declare module 'redux-request-state/tests/selectors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-request-state/index' {
  declare module.exports: $Exports<'redux-request-state'>;
}
declare module 'redux-request-state/index.js' {
  declare module.exports: $Exports<'redux-request-state'>;
}
declare module 'redux-request-state/selectors.js' {
  declare module.exports: $Exports<'redux-request-state/selectors'>;
}
declare module 'redux-request-state/tests/index.js' {
  declare module.exports: $Exports<'redux-request-state/tests/index'>;
}
declare module 'redux-request-state/tests/selectors.js' {
  declare module.exports: $Exports<'redux-request-state/tests/selectors'>;
}
